[package]
name = "dicord-bot"
version = "0.1.0"
authors = ["tomotaka.sasaki <mail@sasaki.games>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
